/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PixijsRouteImport } from './routes/pixijs'
import { Route as IndexRouteImport } from './routes/index'

const PixijsRoute = PixijsRouteImport.update({
  id: '/pixijs',
  path: '/pixijs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pixijs': typeof PixijsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pixijs': typeof PixijsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pixijs': typeof PixijsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pixijs'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pixijs'
  id: '__root__' | '/' | '/pixijs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PixijsRoute: typeof PixijsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pixijs': {
      id: '/pixijs'
      path: '/pixijs'
      fullPath: '/pixijs'
      preLoaderRoute: typeof PixijsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PixijsRoute: PixijsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
